Repository subspace/pulsar, pull requests merged in 2022-11, with the labels that each got.

#20 Spantrace
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/commands/init.rs
  src/config.rs
  src/main.rs
  src/utils.rs
Labels: enhancement

#21 Quiet mode
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/main.rs
  src/utils.rs
Labels: core-implementation

#23 Farm progress bar
  Cargo.lock
  Cargo.toml
  src/commands.rs
  src/commands/farm.rs
  src/commands/wipe.rs
  src/config.rs
  src/main.rs
  src/utils.rs
Labels: core-implementation

#26 Farm info
  Cargo.lock
  Cargo.toml
  rust-toolchain.toml
  src/commands/farm.rs
  src/commands/init.rs
  src/commands/wipe.rs
  src/config.rs
  src/main.rs
  src/summary.rs
  src/utils.rs
Labels: core-implementation

#30 initial readme
  README.md
Labels: documentation

#32 Format and clean up README
  README.md
  images/culture.jpeg
  images/subspace-cli-prompt.png
Labels: documentation

#31 info command implemented
  .github/workflows/ci-tests.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  src/commands.rs
  src/commands/farm.rs
  src/commands/info.rs
  src/commands/init.rs
  src/config.rs
  src/main.rs
  src/summary.rs
Labels: core-implementation

#46 license
  LICENSE.md
Labels: documentation

#38 docs
  rust-toolchain.toml
  src/commands/farm.rs
  src/commands/info.rs
  src/commands/init.rs
  src/commands/wipe.rs
  src/config.rs
  src/main.rs
  src/summary.rs
  src/utils.rs
Labels: documentation

#41 release workflow - without signing
  .github/workflows/release.yml
  Cargo.toml
Labels: dev-ops

#51 Node settings
  .github/workflows/ci-tests.yml
  Cargo.lock
  Cargo.toml
  rust-toolchain.toml
  src/commands/farm.rs
  src/commands/init.rs
  src/commands/wipe.rs
  src/config.rs
  src/summary.rs
Labels: bug, enhancement

#52 Delete LICENSE
  LICENSE
Labels: documentation

#57 doc workflow
  .github/workflows/rustdoc.yml
Labels: documentation

#61 Readme update
  README.md
Labels: documentation

#62 parsing the config for wipe should not validate the config
  src/commands/farm.rs
  src/config.rs
Labels: bug

#64 Implement tests and support gemini-3a
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/commands/init.rs
  src/config.rs
  src/main.rs
  src/utils.rs
Labels: core-implementation, tests

#71 Enable force close
  src/main.rs
Labels: bug
