Repository subspace/pulsar, pull requests merged in 2022-12, with the labels that each got.

#69 default dsn
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/commands/init.rs
  src/config.rs
  src/main.rs
  src/utils.rs
Labels: bug, core-implementation

#75 new chain spec
  Cargo.lock
  Cargo.toml
  src/config.rs
Labels: core-implementation

#76 fix serialization
  src/config.rs
Labels: bug

#78 Fix farmed blocks issue
  src/commands/farm.rs
  src/commands/wipe.rs
  src/config.rs
Labels: bug

#80 fix summary bug & remove unnecessary directive
  src/commands/farm.rs
  src/commands/info.rs
  src/summary.rs
  src/utils.rs
Labels: bug

#83 better error handling
  src/config.rs
Labels: bug

#88 update version to 0.1.3
  Cargo.lock
  Cargo.toml
Labels: bug

#91 Wasmtime downgrade fix
  .github/workflows/ci-tests.yml
  Cargo.lock
  Cargo.toml
Labels: bug

#94 Fix readme badges
  README.md
Labels: bug, documentation

#95 Inline sdk configs
  Cargo.lock
  Cargo.toml
  src/config.rs
Labels: enhancement
