Repository subspace/pulsar, pull requests merged in 2023-04, with the labels that each got.

#166 wipe and info revamp, add console tracing
  Cargo.lock
  Cargo.toml
  src/commands/info.rs
  src/commands/wipe.rs
  src/config.rs
  src/main.rs
  src/summary.rs
  src/utils.rs
Labels: enhancement

#168 fix release and discord release notifier workflows
  .github/workflows/release-notifier.yml
  .github/workflows/release.yml
  Cargo.toml
Labels: bug, dev-ops

#175 implement node and plot improvements
  src/commands/init.rs
  src/tests.rs
  src/utils.rs
Labels: enhancement

#176 update sdk rev
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/config.rs
Labels: maintenance

#178 Summary bug fix
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/summary.rs
Labels: bug

#177 Arrow keys
  Cargo.lock
  Cargo.toml
  src/commands/info.rs
  src/commands/wipe.rs
  src/config.rs
  src/main.rs
Labels: enhancement

#180 Add helper traits to convert anyhow error to eyre
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/config.rs
  src/utils.rs
Labels: bug

#181 open log folder with default file browser
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/utils.rs
Labels: enhancement
