Repository subspace/pulsar, pull requests merged in 2023-06, with the labels that each got.

#206 Add Step to Notify `subspace-docs` Repository of New Releases
  .github/workflows/release-notifier.yml
Labels: documentation, enhancement

#208 disable rotation with argument
  src/commands/farm.rs
  src/main.rs
  src/utils.rs
Labels: enhancement

#211 fixing parallel stream update logic, and some minor things like namings
  .cargo/config.toml
  src/commands/farm.rs
Labels: bug
