Repository subspace/pulsar, pull requests merged in 2023-03, with the labels that each got.

#116 fix typo
  src/commands/init.rs
  src/config.rs
Labels: bug

#119 update the current line instead of appending new line
  src/commands/farm.rs
Labels: enhancement

#121 update sdk and version
  Cargo.lock
  Cargo.toml
Labels: maintenance

#125 Config revamp
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/commands/info.rs
  src/commands/init.rs
  src/commands/wipe.rs
  src/config.rs
  src/main.rs
  src/summary.rs
  src/utils.rs
Labels: enhancement, core-implementation

#133 Update sdk & overhaul farmer
  .cargo/config.toml
  .github/workflows/ci-tests.yml
  .github/workflows/release.yml
  .github/workflows/rustdoc.yml
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/commands/init.rs
  src/config.rs
  src/main.rs
Labels: bug, maintenance

#136 Allow supplying extra substrate options
  src/config.rs
  src/utils.rs
Labels: enhancement

#139 Update sdk
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
Labels: enhancement, maintenance

#141 support gemini3c again
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/config.rs
Labels: maintenance

#143 update sdk
  Cargo.lock
  Cargo.toml
Labels: maintenance

#144 Do not panic if we done with plotting
  src/commands/farm.rs
Labels: bug

#145 fix executable name and bump version
  Cargo.lock
  Cargo.toml
  src/utils.rs
Labels: bug

#147 Version command
  src/main.rs
  src/utils.rs
Labels: bug, enhancement

#149 update sdk
  Cargo.lock
  Cargo.toml
Labels: bug, maintenance

#151 Fix extra options bug and add regression test
  src/utils.rs
Labels: bug

#156 farmer and node flags for wipe command
  src/commands/wipe.rs
  src/main.rs
  src/utils.rs
Labels: enhancement

#157 fix farmer silent exit
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/commands/init.rs
Labels: bug

#159 Fix macos signing
  .github/workflows/Entitlements.plist
  .github/workflows/release.yml
Labels: bug

#160 Implement Discord Webhook for Release Notification
  .github/workflows/release-notifier.yml
Labels: enhancement

#161 Gemini 3d
  Cargo.lock
  Cargo.toml
  src/commands/farm.rs
  src/commands/init.rs
  src/config.rs
  src/utils.rs
Labels: core-implementation, maintenance
